### ISSUE TITLE
a mismatch between Kilosort channels number and probefinder

### ISSUE THREAD

**Issue by parviz-gh** [JorritMontijn/UniversalProbeFinder#4]
Hi , for an example recording with 119 recording channel the out put file from probe finder shows me 121 channel. for example I expected that the size of `probe_area_labels_per_depth` would be [119 x 1] equal to number of channels but suprisingly it is not . I checked the number of channel by reading `channel_positions.npy` in Kilosort directory . This mismatch is exist for few examples that I have tried

**Comment by JorritMontijn** [comment]
Hi parviz-gh,

The *_per_depth variables are linear coordinates along your probe, which can be shrunk or extended. If you're reading in SpikeGLX data and want the area locations of your channels, you should use the *_per_cluster variables instead. They're not clusters as such, but if you don't use pre-sorted kilosort data, the ProbeFinder will simply treat each channel as if it's a cluster. So to get the full name of the areas for each channel you can refer to sProbeCoords.sProbeAdjusted.probe_area_full_per_cluster
I should have probably made that clearer in the manual, as it only describes what happens with pre-sorted data.

I hope this clears things up and let me know if you're still having issues.

Best wishes,
Jorrit

**Comment by parviz-gh** [comment]
Thank you for the response . as far as i underestood you defined probe length in line 62 in function `EL_PrepEphys_KS.m` by defining `dblProbeLength = max(sEphysData.ycoords);` . So what if I changed this line to the number of channel that I am recording from ? . I assume that this doesnt affact location of *_per_cluster variables . since the location of Clusters are equal to the location of channels with highest amplitude for given cluter.

**Comment by JorritMontijn** [comment]
The probe length will influence the initial location of the recording sites/clusters, but as you can see on line 66, you can use a work-around by setting a global gForceProbeLength_PH_PrepEphys to whatever length you need the probe to be in case kilosort's channel-map data is incorrect. Either way, dblProbeLength sets the original size of the probe, so in that sence the *_per_cluster variables will be different, but if you stretch/shrink the probe afterward to the same size and put it in the same location, then the *_per_cluster variables should be identical.

By the way, if you only want to work with the probe channels and not kilosort's clusters, you can also load a directory that has the raw spikeglx files (.meta and .bin) and no kilosort files. Then it will use EL_PrepEphys_SG.m to load the data. Kilosort does some weird and inconsistent data dropping that also differs between versions of kilosort, so if you want to make sure that your channel locations are correct, I suggest you try looking at your probe location with the spikeglx data. And in case the stretch of your recording sites is not 3840 microns long, you can use the same global gForceProbeLength_PH_PrepEphys trick (this only works for contiguous recording sites with constant spacing though).

**Comment by JorritMontijn** [comment]
In the v1.1 update, the ProbeFinder automatically reads the channel map from SpikeGLX, so the probe length issue should be fixed. But let me know if it isn't!
